### ISSUE TITLE
Fix scrapers to remove inline javascript in ZIM files

### ISSUE THREAD

**Issue by mossroy** [kiwix/kiwix-js#865]
As discussed in #789, browser extensions now enforce some CSP that block inline javascript.
And it might happen in some other contexts, too.

Here is a list of affected scrapers that should be fixed (most critical first):

- [x] https://github.com/openzim/gutenberg/issues/145 : main page unusable, other pages seem to work well
- [x] https://github.com/openzim/nautilus/issues/34 : main mage unusable, other pages seem to work well
- [x] https://github.com/openzim/phet/issues/134 : main page unusable, other pages seem to work well
- [x] https://github.com/openzim/phet/pull/152
- [x] https://github.com/openzim/youtube/issues/154 : "only" affects the drop-down list of the home page, and loading of the webp-polyfill
- [x] https://github.com/openzim/openedx/issues/168: a lot of inline javascript blocks + some "onclick" attributes
- [x] https://github.com/openzim/sotoki/issues/249 : several inline javascript blocks + some "onerror" attributes on some images
- [x] https://github.com/openzim/mwoffliner/issues/1578 : minor. It seems to block webp-polyfill related code
- [x] https://github.com/openzim/wikihow/issues/108 : minor. It blocks some video-related javascript
- [x] https://github.com/openzim/ted/issues/128 : minor. It seems to block webp-polyfill related code
- [x] https://github.com/openzim/kolibri2zim/issues/39 : minor. It seems to block webp-polyfill related code

NB: please tick the items in the list only when it has been tested with Kiwix-js with a public ZIM file

**Comment by Jaifroid** [comment]
It looks like we might have got as far as we can with this issue. It has become less critical now that we are forced (due to Manifest V3) to use the PWA workaround for the Chromium extension. However, "conceptually" it would be nice to fix the remaining three scrapers. @kelson42 Do you think this issue should now be closed (but leave the unresolved three issues listed above still open)?

**Comment by kelson42** [comment]
Still something to finish, now officially on the plate of @benoit74 ;)

**Comment by benoit74** [comment]
`kolibri` is now done with https://github.com/openzim/kolibri/pull/43, will probably be released very soon with https://github.com/openzim/kolibri/pull/44, please tick the box (I don't have sufficient rights ;o))

**Comment by Jaifroid** [comment]
@benoit74 Wonderful, many thanks! Box duly ticked!

**Comment by benoit74** [comment]
@Jaifroid : I forgot to mention it, you can tick `openedx` as well

As discussed with @kelson42, `gutenberg` is on my plate, I plan to do this in August / early September together will all remaining issues of [2.1.0](https://github.com/openzim/gutenberg/milestone/6)

**Comment by Jaifroid** [comment]
Thank you very much, @benoit74. I've ticked OpenEdx and look forward to Gutenberg in due course!

**Comment by benoit74** [comment]
@Jaifroid: Could you please test:
- gutenberg : https://www.swisstransfer.com/d/e0c06fef-396f-48a0-af13-44fcee91965d (very small ZIM with only few books but multiple authors, bookshelves, languages so we can test most functionalities)
- kolibri : https://mirror.download.kiwix.org/zim/.hidden/dev/africanstorybook.org_en_all_2023-07.zim

Unfortunately I cannot provide a ZIM to test openedx because we have no more active recipes on Zimfarm + other issues preventing the scraper to operate properly on recent openedx versions (https://github.com/openzim/openedx/issues/175)

**Comment by kelson42** [comment]
@benoit74 Thank you very to have fixed the last scrapers. I can't wait to see that ticket closed!

**Comment by Jaifroid** [comment]
@benoit74 Thank you very much indeed. I've tested the new Gutenberg ZIM in the Chromium extension in the "Service Worker Local" mode, and I can confirm that books now display and load correctly, and all JS seems to be functioning as expected.

I'm still downloading the African Story Book, so will report back on that, but it's looking great!

**Comment by Jaifroid** [comment]
I've now tested the African Story Book ZIM in Chromium with Service Worker Local mode (this is the mode where inline JS is blocked), and I confirm that it all looks good. The EPUB viewer, which I think is the main piece of dynamic code here, works perfectly with this version.

@benoit74 Many thanks indeed. So I think we can finally close this issue if everyone is happy. 😊

**Comment by Jaifroid** [comment]
Thanks once again!
